import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
    <head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>BeautyShelf - Premium Cosmetics & Skincare</title>
      <meta name="description" content="Shop the finest cosmetics, skincare, haircare, and beauty products at BeautyShelf - your beauty emporium." />
      <meta name="author" content="Lovable" />

      <meta property="og:title" content="BeautyShelf - Premium Cosmetics & Skincare" />
      <meta property="og:description" content="Shop the finest cosmetics, skincare, haircare, and beauty products at BeautyShelf - your beauty emporium." />
      <meta property="og:type" content="website" />
      <meta property="og:image" content="https://lovable.dev/opengraph-image-p98pqg.png" />

      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@lovable_dev" />
      <meta name="twitter:image" content="https://lovable.dev/opengraph-image-p98pqg.png" />
    </head>

    <body>
      <div id="root"></div>
      <script src="https://cdn.gpteng.co/gptengineer.js" type="module"></script>
      <script type="module" src="/src/main.tsx"></script>

      <Header />
      {children}
    </body>
  </html>


  );
}
